$(document).ready(function(){
    $('.slider').slick({
        arrows:true,
        dots:true,
        adaptiveHeight: true,
        slidesToShow: 1,
        // slidesToScroll: 3,
        speed: 1000,
        easing: 'ease',
        // infinite: false,
        initialSlide: 1,
        // autoplay: true,
        // autoplaySpeed: 500,
        // pauseOnFocus: true,
        pauseOnHover: true,
        // pauseOnDotsHover: true,
        // draggable: false, 
        // swipe: true,
        // touchThreshold: 5,
        // touchMove: false,
        centerMode: false,
        waitForAnimate: false,
        variableWidth: false,
        // rows: 2,
        // slidesPerRow: 2,
        // vertical: true,
        // verticalSwiping: true,
        
    });
});